# Generated by Django 3.1 on 2022-04-09 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMoneyWithDrawalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_amount', models.CharField(max_length=50)),
                ('Withdrawal_request_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=50)),
                ('branch_id', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('bank_country', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
