# Generated by Django 3.2.16 on 2023-08-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyment_withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoneywithdrawalstatus',
            name='withraw_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermoneywithdrawalstatus',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
