# Generated by Django 3.2.18 on 2024-04-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyment_withdraw', '0002_auto_20230814_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdetails',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='bank_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='branch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
