# Generated by Django 3.2.18 on 2024-09-29 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyment_withdraw', '0003_auto_20240416_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoneywithdrawalstatus',
            name='Withdrawal_request_date',
            field=models.DateField(blank=True, db_column='Withdrawal_request_date', default=django.utils.timezone.now, null=True),
        ),
    ]
