# Generated by Django 3.2.18 on 2025-08-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyment_withdraw', '0004_alter_usermoneywithdrawalstatus_withdrawal_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usermoneywithdrawalstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
