# Generated by Django 4.2.7 on 2024-01-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cycle_days', models.IntegerField()),
                ('start_date', models.DateField()),
                ('grace_period', models.IntegerField()),
                ('description', models.TextField()),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='chamas.chama')),
            ],
        ),
    ]
