# Generated by Django 4.2.7 on 2024-01-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0003_chamamember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chama',
            name='amount',
        ),
    ]
