# Generated by Django 4.2.7 on 2024-01-20 21:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0004_remove_chama_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('max_loan_amount', models.IntegerField()),
                ('grace_period', models.IntegerField()),
                ('late_fine', models.IntegerField()),
                ('installment_percentage', models.IntegerField()),
                ('intrest_rate', models.IntegerField()),
                ('description', models.TextField()),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_types', to='chamas.chama')),
            ],
        ),
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('intrest_rate', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='application', max_length=10)),
                ('repayment_term', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('applied_on', models.DateTimeField(default=datetime.datetime(2024, 1, 20, 21, 40, 1, 49076, tzinfo=datetime.timezone.utc))),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loans', to='chamas.chamamember')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_records', to='chamas.loantype')),
            ],
        ),
        migrations.CreateModel(
            name='FineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_types', to='chamas.chama')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_types', to='chamas.loantype')),
            ],
        ),
        migrations.CreateModel(
            name='FineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fine_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='active', max_length=55)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 1, 20, 21, 40, 1, 52069, tzinfo=datetime.timezone.utc))),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2024, 1, 20, 21, 40, 1, 52069, tzinfo=datetime.timezone.utc))),
                ('fine_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fine_items', to='chamas.finetype')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fines', to='chamas.chamamember')),
            ],
        ),
    ]
