# Generated by Django 4.2.7 on 2024-01-20 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0005_loantype_loanitem_finetype_fineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fineitem',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fineitem',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='applied_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
