# Generated by Django 4.2.7 on 2024-01-21 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0006_alter_fineitem_created_alter_fineitem_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenses', to='chamas.chama')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chama_expenses', to='chamas.chamamember')),
            ],
        ),
    ]
