# Generated by Django 4.2.7 on 2024-01-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0007_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanitem',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
