# Generated by Django 4.2.7 on 2024-01-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0008_alter_loanitem_total_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitem',
            name='chama',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='loans', to='chamas.chama'),
        ),
    ]
