# Generated by Django 4.2.7 on 2024-01-21 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0009_loanitem_chama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanitem',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
