# Generated by Django 4.2.7 on 2024-01-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0010_alter_loanitem_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fineitem',
            name='loan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fines', to='chamas.loanitem'),
        ),
    ]
