# Generated by Django 4.2.7 on 2024-01-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0011_fineitem_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitem',
            name='total_amount_to_be_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
