# Generated by Django 4.2.7 on 2024-01-27 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0012_loanitem_total_amount_to_be_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forGroup', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='chamas.chama')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='savings', to='chamas.chamamember')),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='savings', to='chamas.savingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='chamas.chama')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('forGroup', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='chamas.chama')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incomes', to='chamas.chamamember')),
            ],
        ),
    ]
