# Generated by Django 4.2.7 on 2024-01-27 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0013_savingtype_saving_investment_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='user_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
