# Generated by Django 4.2.7 on 2024-01-27 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0014_investment_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='user_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
