# Generated by Django 4.2.7 on 2024-02-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0015_income_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('amount_expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='chamas.contribution')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_records', to='chamas.chamamember')),
            ],
        ),
    ]
