# Generated by Django 4.2.7 on 2024-02-03 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0016_contributionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_types', to='chamas.chama')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('forGroup', models.BooleanField()),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chamas.chama')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chamas.chamamember')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications', to='chamas.notificationtype')),
            ],
        ),
    ]
