# Generated by Django 4.2.7 on 2024-02-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0017_notificationtype_notificationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamamember',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
