# Generated by Django 4.2.7 on 2024-02-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0019_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamamember',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileImages'),
        ),
    ]
