# Generated by Django 4.2.7 on 2024-02-09 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamas', '0020_chamamember_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chama',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chama',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type', to='chamas.chamatype'),
        ),
        migrations.AlterField(
            model_name='chamamember',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member', to='chamas.role'),
        ),
        migrations.AlterField(
            model_name='contributionrecord',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_records', to='chamas.chamamember'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='chama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenses', to='chamas.chama'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chama_expenses', to='chamas.chamamember'),
        ),
        migrations.AlterField(
            model_name='fineitem',
            name='fine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fine_items', to='chamas.finetype'),
        ),
        migrations.AlterField(
            model_name='fineitem',
            name='loan',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fines', to='chamas.loanitem'),
        ),
        migrations.AlterField(
            model_name='fineitem',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fines', to='chamas.chamamember'),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='chama',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loans', to='chamas.chama'),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loans', to='chamas.chamamember'),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_records', to='chamas.loantype'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='saving_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='savings', to='chamas.savingtype'),
        ),
    ]
