# Generated by Django 4.2.7 on 2024-02-11 05:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0021_alter_chama_created_by_alter_chama_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_date', models.DateTimeField()),
                ('type', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forGroup', models.BooleanField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_reports', to='chamas.chama')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cashflow_reports', to='chamas.chamamember')),
            ],
        ),
    ]
