# Generated by Django 4.2.7 on 2024-02-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0022_cashflowreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowreport',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
