# Generated by Django 4.2.7 on 2024-02-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0023_alter_cashflowreport_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamamember',
            name='balance',
        ),
    ]
