# Generated by Django 3.2.18 on 2024-02-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0024_remove_chamamember_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='next_due',
            field=models.DateTimeField(null=True),
        ),
    ]
