# Generated by Django 4.2.7 on 2024-02-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0025_contribution_next_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='next_due',
            field=models.DateField(null=True),
        ),
    ]
