# Generated by Django 4.2.7 on 2024-02-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0026_alter_contribution_next_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='investment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='chamas.investment'),
        ),
    ]
