# Generated by Django 4.2.7 on 2024-02-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0027_income_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fineitem',
            name='contribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fines', to='chamas.contributionrecord'),
        ),
        migrations.AddField(
            model_name='fineitem',
            name='forContribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fineitem',
            name='forLoan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fineitem',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fineitem',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
