# Generated by Django 4.2.7 on 2024-02-16 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0028_fineitem_contribution_fineitem_forcontribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fineitem',
            name='contribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fines', to='chamas.contribution'),
        ),
    ]
