# Generated by Django 4.2.7 on 2024-02-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0029_alter_fineitem_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finetype',
            name='loan_type',
        ),
    ]
