# Generated by Django 4.2.7 on 2024-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0030_remove_finetype_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fineitem',
            name='contribution_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
