# Generated by Django 4.2.7 on 2024-02-23 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0031_fineitem_contribution_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionrecord',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
