# Generated by Django 4.2.7 on 2024-02-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0032_contributionrecord_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='due',
            field=models.IntegerField(default=0),
        ),
    ]
