# Generated by Django 4.2.7 on 2024-02-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0033_loantype_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantype',
            name='installment_percentage',
        ),
    ]
