# Generated by Django 4.2.7 on 2024-02-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0034_remove_loantype_installment_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionrecord',
            name='chama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_records', to='chamas.chama'),
        ),
    ]
