# Generated by Django 4.2.7 on 2024-02-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0035_contributionrecord_chama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamamember',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
