# Generated by Django 4.2.7 on 2024-03-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0037_alter_chamamember_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='schedule',
            field=models.CharField(default='monthly', max_length=55),
        ),
    ]
