# Generated by Django 4.2.7 on 2024-03-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0038_loantype_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='cycle_days',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='next_due',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='start_date',
        ),
        migrations.CreateModel(
            name='ContributionCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='chamas.chama')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='chamas.contribution')),
            ],
        ),
        migrations.AddField(
            model_name='contributionrecord',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cluster_records', to='chamas.contributioncluster'),
        ),
    ]
