# Generated by Django 4.2.7 on 2024-03-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0039_remove_contribution_cycle_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionrecord',
            name='cluster',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.DeleteModel(
            name='ContributionCluster',
        ),
    ]
