# Generated by Django 4.2.11 on 2024-03-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0040_alter_contributionrecord_cluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
