# Generated by Django 4.2.11 on 2024-03-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0041_contribution_end_date_contribution_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantype',
            old_name='due',
            new_name='max_due',
        ),
        migrations.RemoveField(
            model_name='loanitem',
            name='repayment_term',
        ),
        migrations.AddField(
            model_name='loanitem',
            name='due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanitem',
            name='schedule',
            field=models.CharField(default='monthly', max_length=55),
        ),
    ]
