# Generated by Django 3.2.18 on 2024-03-05 06:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamas', '0042_rename_due_loantype_max_due_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chamamember',
            unique_together={('user', 'group')},
        ),
    ]
