# Generated by Django 4.2.11 on 2024-03-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0043_alter_chamamember_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamamember',
            name='member_id',
            field=models.IntegerField(null=True),
        ),
    ]
