# Generated by Django 4.2.11 on 2024-03-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0044_chamamember_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamamember',
            name='member_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
