# Generated by Django 4.2.11 on 2024-03-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0046_alter_cashflowreport_member_alter_chama_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamamember',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
