# Generated by Django 4.2.11 on 2024-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0047_chamamember_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitem',
            name='next_due',
            field=models.DateTimeField(null=True),
        ),
    ]
