# Generated by Django 4.2.11 on 2024-03-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0048_loanitem_next_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanitem',
            name='status',
            field=models.CharField(default='application', max_length=50),
        ),
        migrations.AlterField(
            model_name='savingtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
