# Generated by Django 3.2.18 on 2024-05-13 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamas', '0049_alter_loanitem_status_alter_savingtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamamember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
