# Generated by Django 3.2.18 on 2024-09-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0050_alter_chamamember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowreport',
            name='forGroup',
            field=models.BooleanField(db_column='forGroup'),
        ),
        migrations.AlterField(
            model_name='fineitem',
            name='forContribution',
            field=models.BooleanField(db_column='forContribution', default=False),
        ),
        migrations.AlterField(
            model_name='fineitem',
            name='forLoan',
            field=models.BooleanField(db_column='forLoan', default=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='forGroup',
            field=models.BooleanField(db_column='forGroup', default=False),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='forGroup',
            field=models.BooleanField(db_column='forGroup'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='forGroup',
            field=models.BooleanField(db_column='forGroup', default=False),
        ),
    ]
