# Generated by Django 3.2.18 on 2024-09-29 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamas', '0051_auto_20240930_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamamember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributionrecord',
            name='chama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_records', to='chamas.chama'),
            preserve_default=False,
        ),
    ]
