# Generated by Django 3.2.18 on 2024-09-29 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0052_auto_20240930_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='investment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='chamas.investment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chamas.chamamember'),
            preserve_default=False,
        ),
    ]
