# Generated by Django 3.2.18 on 2024-09-30 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamas', '0053_auto_20240930_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamamember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributionrecord',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_records', to='chamas.chama'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='chamas.chama'),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='chamas.chamamember'),
        ),
    ]
