# Generated by Django 3.2.18 on 2025-05-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0054_auto_20240930_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionrecord',
            name='cluster',
        ),
    ]
