# Generated by Django 3.2.18 on 2025-07-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0001_add_document_fields'),
        ('chamas', '0056_remove_contribution_grace_period_and_end_date'),
    ]

    operations = [
    ]
