# Generated by Django 3.2.18 on 2025-08-03 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0057_merge_20250729_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='forGroup',
            field=models.BooleanField(db_column='forGroup', default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='chamas.chamamember'),
        ),
    ]
