# Generated by Django 3.2.18 on 2025-08-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0058_add_contribution_record_to_fineitem'),
        ('chamas', '0058_auto_20250803_1108'),
    ]

    operations = [
    ]
