# Generated by Django 3.2.18 on 2024-09-19 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achieved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saving_type', models.CharField(choices=[('regular', 'Regular Saving'), ('fixed', 'Fixed Saving')], max_length=10)),
                ('goal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('goal_description', models.CharField(blank=True, max_length=100, null=True)),
                ('shareable_link', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.CharField(default='Yes', max_length=100)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=10, null=True)),
                ('payment_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('achieved', 'Achieved')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_deposit', models.DecimalField(decimal_places=2, default=0.06, max_digits=10)),
                ('fixed_deposit', models.DecimalField(decimal_places=2, default=0.08, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='tax_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_value', models.DecimalField(decimal_places=2, default=0.2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GroupGoalMember_contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_date', models.DateField(blank=True, null=True)),
                ('is_withdraw', models.CharField(blank=True, default='No', max_length=10, null=True)),
                ('group_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goals.groupgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupGoalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goals.groupgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupGoalActivites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goals.groupgoal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saving_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saving_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('group_goal_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.CharField(default='Yes', max_length=100)),
                ('saving_type', models.CharField(choices=[('regular', 'Regular Saving'), ('fixed', 'Fixed Saving')], max_length=10)),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_to_save_per_notification', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_months', models.PositiveIntegerField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=10, null=True)),
                ('payment_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('goal_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluation_date', models.DateField(blank=True, null=True)),
                ('is_withdraw', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_withdraw', models.CharField(blank=True, default='No', max_length=10, null=True)),
                ('deposit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='Goals.goal')),
            ],
        ),
    ]
