# Generated by Django 5.2.7 on 2025-12-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0003_alter_groupgoalactivites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='milestone_50_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='milestone_75_shown',
            field=models.BooleanField(default=False),
        ),
    ]
