# Generated by Django 5.2.7 on 2025-12-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0004_goal_milestone_50_shown_goal_milestone_75_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupgoal',
            name='milestone_50_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupgoal',
            name='milestone_75_shown',
            field=models.BooleanField(default=False),
        ),
    ]
