# Generated by Django 5.2.7 on 2025-12-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0005_groupgoal_milestone_50_shown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expresssaving',
            name='is_withdraw',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
    ]
