# Generated by Django 5.2.7 on 2025-12-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0006_alter_expresssaving_is_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='expresssaving',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='deposit', max_length=20),
        ),
    ]
