# Generated by Django 5.2.7 on 2026-01-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0007_expresssaving_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalCategory',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('default_image', models.CharField(max_length=200)),
                ('default_icon', models.CharField(max_length=50)),
                ('theme_color', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Goal Category',
                'verbose_name_plural': 'Goal Categories',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Category determines the goal's image and theme", null=True, on_delete=django.db.models.deletion.SET_NULL, to='Goals.goalcategory'),
        ),
    ]
