# Generated by Django 5.2.7 on 2026-01-09 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person submitting the message', max_length=200)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=300)),
                ('message', models.TextField(help_text='The actual message content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was submitted')),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this message has been handled')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the message was marked as resolved', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of submitter', null=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contact_con_created_00b9df_idx'), models.Index(fields=['is_resolved'], name='contact_con_is_reso_fda853_idx')],
            },
        ),
    ]
