# Generated by Django 3.1 on 2021-11-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=225)),
                ('No_of_chamas_memebrs', models.CharField(max_length=225)),
                ('frequency_of_contribution', models.CharField(max_length=225)),
                ('amount_per_contribution', models.CharField(max_length=225)),
                ('contribution_turn', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('category', models.CharField(max_length=225)),
            ],
        ),
    ]
