# Generated by Django 3.1 on 2021-11-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chama_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=225)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('No_of_chamas_memebrs', models.CharField(max_length=225)),
                ('awarded_turn', models.CharField(blank=True, max_length=225, null=True)),
                ('members_awarded', models.CharField(blank=True, max_length=225, null=True)),
                ('progress', models.CharField(blank=True, max_length=225, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chama_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=225)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('No_of_chamas_memebrs', models.CharField(max_length=225)),
                ('awarded_turn', models.CharField(blank=True, max_length=225, null=True)),
                ('members_awarded', models.CharField(blank=True, max_length=225, null=True)),
                ('progress', models.CharField(blank=True, max_length=225, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
