# Generated by Django 3.1 on 2021-11-25 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0002_chama_one_chama_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chamas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=700, null=True)),
                ('No_of_people', models.CharField(max_length=225)),
                ('frequency_of_contribution', models.CharField(max_length=225)),
                ('contribution_turn', models.CharField(blank=True, max_length=225, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=225)),
                ('active', models.CharField(max_length=225)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.category')),
            ],
        ),
        migrations.CreateModel(
            name='contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('fined_amount', models.FloatField(blank=True, null=True)),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('chamas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chamas')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('chamas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chamas')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('chamas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chamas')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_joined_chamas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Awarded', models.CharField(blank=True, max_length=225, null=True)),
                ('Award_turn', models.CharField(blank=True, max_length=225, null=True)),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('chamas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chamas')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='chama_one',
        ),
        migrations.DeleteModel(
            name='chama_two',
        ),
        migrations.DeleteModel(
            name='Pre_Registration',
        ),
    ]
