# Generated by Django 3.1 on 2022-02-05 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0006_auto_20220120_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Category Details'),
        ),
        migrations.AlterField(
            model_name='category',
            name='inserted_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Inserted On'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='Award_turn',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Award Turn'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='No_of_people',
            field=models.CharField(max_length=225, verbose_name='No. of People'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='active',
            field=models.CharField(max_length=225, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='amount',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Chamas Amount'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.category', verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='contribution_turn',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Contribution Turn'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Chamas End Date'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='frequency_of_contribution',
            field=models.CharField(max_length=225, verbose_name='Frequency of Contribution'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='inserted_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Inserted On'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='name',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Chamas Name'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Chamas Start Date'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='status',
            field=models.CharField(max_length=225, verbose_name='Chamas Status'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='updated_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='chamas_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chamas', verbose_name='Chamas Name'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='fined_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Fined Amount'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='inserted_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Inserted On'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='updated_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='chamas_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chamas', verbose_name='Chamas Name'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Notification Details'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='inserted_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Inserted On'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_text',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Notification Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name'),
        ),
    ]
