# Generated by Django 3.1 on 2022-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='withdrawal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
