# Generated by Django 3.1 on 2022-06-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_wallet_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='chamas_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chamas'),
        ),
    ]
