# Generated by Django 3.1 on 2022-08-20 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_auto_20220623_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='mpesa_body_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Body is')),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Inserted On')),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Updated On')),
            ],
        ),
    ]
