# Generated by Django 3.1 on 2022-08-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_mpesa_body_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesa_body_test',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Description'),
        ),
    ]
