# Generated by Django 3.1 on 2022-10-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_mpesa_body_test_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='amount',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='category',
            name='frequency',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='category',
            name='members',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Members'),
        ),
    ]
