# Generated by Django 3.1 on 2022-10-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_auto_20221016_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamas',
            name='contribution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contribution Date'),
        ),
    ]
