# Generated by Django 3.1 on 2022-10-30 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_chamas_contribution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamas',
            name='contribution_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Contribution Date'),
        ),
    ]
