# Generated by Django 3.1 on 2022-10-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_auto_20221030_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamas',
            name='contribution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contribution Date'),
        ),
    ]
