# Generated by Django 3.2.16 on 2022-12-22 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0016_auto_20221030_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving_Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peer_to_Peer_Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
