# Generated by Django 3.2.18 on 2024-09-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_peer_to_peer_wallet_saving_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamas',
            name='Award_turn',
            field=models.CharField(blank=True, db_column='Award_turn', max_length=225, null=True, verbose_name='Award Turn'),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='Awarded',
            field=models.CharField(blank=True, db_column='Awarded', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='chamas',
            name='No_of_people',
            field=models.CharField(db_column='No_of_people', max_length=225, verbose_name='No. of People'),
        ),
    ]
