# Generated by Django 3.2.18 on 2024-09-29 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_auto_20240930_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='chamas_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chamas'),
            preserve_default=False,
        ),
    ]
