# Generated by Django 3.2.18 on 2024-09-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_alter_wallet_chamas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='chamas_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.chamas'),
        ),
    ]
