# Generated by Django 5.2.7 on 2025-11-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry_go_round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitee_national_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
