# Generated by Django 5.2.7 on 2025-12-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry_go_round', '0002_invitation_invitee_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invitation',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
