# Generated by Django 5.2.7 on 2025-12-15 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry_go_round', '0003_invitation_action_url_invitation_declined_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundCompletionStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_expected_contributions', models.DecimalField(decimal_places=2, help_text='Total amount that should have been collected', max_digits=12)),
                ('total_actual_contributions', models.DecimalField(decimal_places=2, help_text='Total amount actually collected', max_digits=12)),
                ('completion_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of target reached', max_digits=5)),
                ('total_gross_interest', models.DecimalField(decimal_places=2, help_text='Total interest earned before tax', max_digits=12)),
                ('total_tax_deducted', models.DecimalField(decimal_places=2, help_text='Total tax deducted from interest', max_digits=12)),
                ('total_net_interest', models.DecimalField(decimal_places=2, help_text='Total interest after tax', max_digits=12)),
                ('total_paid_out', models.DecimalField(decimal_places=2, help_text='Total amount paid to all members', max_digits=12)),
                ('interest_rate_used', models.DecimalField(decimal_places=2, help_text='Interest rate that was applied', max_digits=5)),
                ('tax_rate_used', models.DecimalField(decimal_places=2, help_text='Tax rate that was applied', max_digits=5)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_snapshot', to='merry_go_round.round')),
            ],
            options={
                'verbose_name': 'Round Completion Stats',
                'verbose_name_plural': 'Round Completion Stats',
                'db_table': 'mgr_round_completion_stats',
            },
        ),
    ]
