# Generated by Django 5.2.7 on 2025-12-17 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merry_go_round', '0004_roundcompletionstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='lookup_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('national_id', 'National ID'), ('link', 'Shareable Link')], default='email', max_length=15),
        ),
        migrations.AddField(
            model_name='invitation',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
