# Generated by Django 3.1 on 2021-10-19 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chamas_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numbers_of_memebrs', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='frequency_of_contri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_of_contribution', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='How_did_you_find',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='no_of_cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_cycle', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('NIC_No', models.IntegerField(blank=True, max_length=8, null=True, unique=True)),
                ('physical_address', models.CharField(blank=True, max_length=40, null=True)),
                ('picture', models.ImageField(blank=True, upload_to='ProfileImages')),
                ('No_of_chamas_memebrs', models.IntegerField(blank=True, max_length=225, null=True)),
                ('frequency_of_contribution', models.CharField(blank=True, max_length=225, null=True)),
                ('amount_per_contribution', models.IntegerField(blank=True, max_length=225, null=True)),
                ('no_of_cycles', models.IntegerField(blank=True, max_length=225, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=225, null=True)),
                ('how_did_you_find', models.CharField(blank=True, max_length=225, null=True)),
                ('gender', models.CharField(blank=True, max_length=25, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
