# Generated by Django 3.1 on 2021-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='amount_per_contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_contribution', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='chamas_members',
            name='Numbers_of_memebrs',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='no_of_cycle',
            name='no_of_cycle',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='profile',
            name='NIC_No',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='No_of_chamas_memebrs',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='amount_per_contribution',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='no_of_cycles',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
