# Generated by Django 3.1 on 2021-10-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211019_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='No_of_chamas_memebrs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='amount_per_contribution',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='frequency_of_contribution',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='no_of_cycles',
        ),
    ]
