# Generated by Django 3.1 on 2021-10-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='NIC_No',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
