# Generated by Django 3.2.18 on 2024-09-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211022_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='NIC_No',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
