# Generated by Django 3.2.18 on 2024-09-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_nic_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='NIC_No',
            field=models.CharField(blank=True, db_column='NIC_No', max_length=25, null=True, unique=True),
        ),
    ]
