# Generated by Django 5.2.7 on 2026-01-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20250803_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
