# Generated by Django 3.2.18 on 2025-05-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamas', '0054_auto_20240930_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_contribution', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted_member', models.TextField()),
                ('submitted_chama', models.TextField()),
                ('retrieved_chama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_contribution_records', to='chamas.chama')),
                ('retrieved_contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_botrecords', to='chamas.contribution')),
            ],
        ),
    ]
