# Generated by Django 3.2.18 on 2025-05-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0054_auto_20240930_1636'),
        ('bot', '0002_botfine'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.TextField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted_chama', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('retrieved_chama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_loan_records', to='chamas.chama')),
                ('updated_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_updates', to='chamas.loanitem')),
            ],
        ),
    ]
