# Generated by Django 3.2.18 on 2025-05-09 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0054_auto_20240930_1636'),
        ('bot', '0003_botloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontribution',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chama_bot_contributions', to='chamas.chama'),
        ),
        migrations.AddField(
            model_name='botfine',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chama_bot_fines', to='chamas.chama'),
        ),
        migrations.AddField(
            model_name='botloan',
            name='chama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chama_bot_loans', to='chamas.chama'),
        ),
    ]
