# Generated by Django 3.2.18 on 2025-05-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20250509_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontribution',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botcontribution',
            name='member_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='botfine',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botloan',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
