# Generated by Django 3.2.18 on 2025-05-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0054_auto_20240930_1636'),
        ('bot', '0005_auto_20250510_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('id_number', models.TextField()),
                ('phone', models.TextField()),
                ('role', models.TextField()),
                ('chama_name', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_members', to='chamas.chamamember')),
            ],
        ),
    ]
