# Generated by Django 3.2.18 on 2025-05-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0054_auto_20240930_1636'),
        ('bot', '0006_botmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmember',
            name='chama',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_members', to='chamas.chama'),
        ),
    ]
