# Generated by Django 3.2.18 on 2025-05-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0055_remove_contributionrecord_cluster'),
        ('bot', '0007_botmember_chama'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontribution',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_records', to='chamas.contributionrecord'),
        ),
    ]
