# Generated by Django 3.2.18 on 2025-05-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_botcontribution_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontribution',
            name='sender',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='botfine',
            name='sender',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='botloan',
            name='sender',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='botmember',
            name='sender',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='MemberFraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_fraud', to='bot.botmember')),
            ],
        ),
        migrations.CreateModel(
            name='LoanFraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_fraud', to='bot.botloan')),
            ],
        ),
        migrations.CreateModel(
            name='FineFraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_fraud', to='bot.botfine')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionFraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_fraud', to='bot.botcontribution')),
            ],
        ),
    ]
