# Generated by Django 3.2.18 on 2025-05-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20250519_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcontribution',
            name='sender',
            field=models.TextField(blank=True, default=''),
        ),
    ]
