# Generated by Django 5.2.7 on 2025-11-24 09:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total balance (available + locked)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance available for use/withdrawal', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance locked for pending operations', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='KES', help_text='ISO 4217 currency code', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', help_text='Wallet operational status', max_length=20)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount deposited (all time)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount withdrawn (all time)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for audit trail')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Main Wallet',
                'verbose_name_plural': 'Main Wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, help_text='Unique transaction reference', max_length=100, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Client-provided or M-Pesa receipt for idempotent operations', max_length=100, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('mpesa_deposit', 'M-Pesa Deposit'), ('mpesa_withdraw', 'M-Pesa Withdrawal'), ('transfer_to_mgr', 'Transfer to MGR Wallet'), ('transfer_from_mgr', 'Transfer from MGR Wallet'), ('transfer_to_goals', 'Transfer to Goals'), ('transfer_from_goals', 'Transfer from Goals'), ('lock', 'Funds Locked'), ('unlock', 'Funds Unlocked'), ('adjustment', 'Admin Adjustment'), ('migration', 'Balance Migration'), ('reversal', 'Transaction Reversal')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='KES', help_text='ISO 4217 currency code', max_length=3)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, help_text='M-Pesa transaction receipt', max_length=100, null=True)),
                ('related_app', models.CharField(blank=True, choices=[('mgr', 'Merry-Go-Round'), ('goals', 'Wekeza Goals'), ('chamaz', 'Chamaz'), ('system', 'System')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction data (Goal ID, Round ID, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.mainwallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('to_mgr', 'To MGR Wallet'), ('from_mgr', 'From MGR Wallet'), ('to_goals', 'To Goals'), ('from_goals', 'From Goals')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('destination_app', models.CharField(max_length=50)),
                ('destination_id', models.IntegerField(blank=True, help_text='ID of Goal, Round, etc.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transfers', to='wallet.mainwallet')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_transfer', to='wallet.wallettransaction')),
            ],
            options={
                'verbose_name': 'Pending Transfer',
                'verbose_name_plural': 'Pending Transfers',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mainwallet',
            index=models.Index(fields=['user'], name='wallet_main_user_id_184a13_idx'),
        ),
        migrations.AddIndex(
            model_name='mainwallet',
            index=models.Index(fields=['status'], name='wallet_main_status_5414e5_idx'),
        ),
        migrations.AddIndex(
            model_name='mainwallet',
            index=models.Index(fields=['-created_at'], name='wallet_main_created_4574bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='mainwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_wall_wallet__ccf672_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference_number'], name='wallet_wall_referen_a64879_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['idempotency_key'], name='wallet_wall_idempot_442271_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='wallet_wall_transac_2c0a43_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='wallet_wall_status_66d39d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['mpesa_receipt_number'], name='wallet_wall_mpesa_r_f5b691_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingtransfer',
            index=models.Index(fields=['wallet', 'status'], name='wallet_pend_wallet__9c307d_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingtransfer',
            index=models.Index(fields=['-initiated_at'], name='wallet_pend_initiat_2d941f_idx'),
        ),
    ]
