# Generated by Django 5.2.7 on 2026-01-01 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransfer',
            name='auto_approved',
            field=models.BooleanField(default=False, help_text='True if transfer was auto-approved (amount under threshold)'),
        ),
        migrations.AddField(
            model_name='pendingtransfer',
            name='password_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when password was verified', null=True),
        ),
        migrations.AddField(
            model_name='pendingtransfer',
            name='requires_password_verification',
            field=models.BooleanField(default=True, help_text='Whether this transfer requires password verification'),
        ),
        migrations.AlterField(
            model_name='pendingtransfer',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Includes phone_number, withdrawal_method, KYC status, etc.'),
        ),
        migrations.AlterField(
            model_name='pendingtransfer',
            name='status',
            field=models.CharField(choices=[('awaiting_password', 'Awaiting Password Verification'), ('pending', 'Pending Admin Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='awaiting_password', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pendingtransfer',
            index=models.Index(fields=['status', 'auto_approved'], name='wallet_pend_status_90925a_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingtransfer',
            index=models.Index(fields=['amount'], name='wallet_pend_amount_304756_idx'),
        ),
    ]
