# Generated by Django 5.2.7 on 2026-01-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_pendingtransfer_auto_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransfer',
            name='transfer_type',
            field=models.CharField(choices=[('to_mgr', 'To MGR Wallet'), ('from_mgr', 'From MGR Wallet'), ('to_goals', 'To Goals'), ('from_goals', 'From Goals'), ('mpesa_withdraw', 'M-Pesa Withdrawal')], max_length=20),
        ),
    ]
