# Generated by Django 3.2.18 on 2024-06-10 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0017_peer_to_peer_wallet_saving_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Plan', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=2000.0, max_digits=6)),
                ('trial_duration', models.DurationField(default=datetime.timedelta(days=14))),
                ('grace_period', models.DurationField(default=datetime.timedelta(days=2))),
            ],
        ),
        migrations.CreateModel(
            name='ChamaSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('chama', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.chamas')),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
