# Generated by Django 3.2.18 on 2024-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20240611_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamasubscription',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
