# Generated by Django 3.2.18 on 2024-06-11 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_chamasubscription_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('mpesa_receipt_number', models.CharField(max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('result_desc', models.CharField(max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('possible_duplicate', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='chamasubscription',
            name='payment_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.paymentdetail'),
        ),
    ]
