# Generated by Django 3.2.18 on 2024-06-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0050_alter_chamamember_user'),
        ('subscriptions', '0004_auto_20240611_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamasubscription',
            name='chama',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chamas.chama'),
        ),
    ]
