# Generated by Django 3.2.18 on 2024-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_chamasubscription_chama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=0.2, help_text='Tax rate as a percentage', max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='subscription_plans_tax', to='subscriptions.Tax'),
        ),
    ]
