# Generated by Django 3.2.18 on 2024-09-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20240919_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='grace_period',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_duration',
        ),
    ]
