# Generated by Django 3.2.18 on 2024-09-19 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20240919_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='grace_period',
            field=models.DurationField(default=datetime.timedelta(days=2)),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_duration',
            field=models.DurationField(default=datetime.timedelta(days=14)),
        ),
    ]
