# Generated by Django 3.2.18 on 2024-09-20 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20240919_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='chama_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='checkout_request_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
