# Generated by Django 3.2.18 on 2024-09-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20240920_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='chama_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.chamasubscription'),
        ),
    ]
