# Generated by Django 3.2.18 on 2024-09-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_paymentdetail_chama_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamasubscription',
            name='payment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paymentdetail'),
        ),
    ]
