# Generated by Django 3.2.18 on 2024-09-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_chamasubscription_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='period_name',
            field=models.CharField(blank=True, default='year', max_length=100, null=True),
        ),
    ]
