# Generated by Django 3.2.18 on 2024-09-29 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_subscriptionplan_period_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='period_duration',
            field=models.DurationField(default=datetime.timedelta(days=365)),
        ),
    ]
