# Generated by Django 3.2.18 on 2024-09-29 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamas', '0052_auto_20240930_0255'),
        ('subscriptions', '0013_subscriptionplan_period_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamasubscription',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamas.chama'),
        ),
        migrations.AlterField(
            model_name='chamasubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='chamasubscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
