"""
Django settings for Chamabora project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from django.contrib.messages import constants as messages
import cloudinary_storage
from environ import environ
import dj_database_url
from celery.schedules import crontab
from decimal import Decimal
# from firebase_admin import initialize_app

ENV_DIR = Path(__file__).resolve(strict=True).parent.parent
# print(ENV_DIR / '.env')

env = environ.Env(
    DEBUG=(bool, False)
)

try:
    env.read_env(ENV_DIR / '.env')
except FileNotFoundError:
    raise FileNotFoundError("No .env file found. Please create one in the project root directory.")


SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=True)

# Twilio settings with defaults for development
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='dev-twilio-sid')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='dev-twilio-token')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER', default='+1234567890')


CLOUDINARY_STORAGE_CLOUD_NAME = env('CLOUDINARY_STORAGE_CLOUD_NAME')
CLOUDINARY_STORAGE_API_KEY = env('CLOUDINARY_STORAGE_API_KEY')
CLOUDINARY_STORAGE_API_SECRET = env('CLOUDINARY_STORAGE_API_SECRET')

CONSUMER_KEY = env('CONSUMER_KEY')
CONSUMER_SECRET = env('CONSUMER_SECRET')
BUSINESS_SHORT_CODE = env('BUSINESS_SHORT_CODE')
PASSKEY = env('PASSKEY')
CALLBACK_URL=env('CALLBACK_URL', default="https://chamaspace.com/load_money/callback")
INITIATOR_NAME=env('INITIATOR_NAME')
SECURITY_CREDENTIAL=env('SECURITY_CREDENTIAL')

FCM_SERVER_KEY = env('FCM_SERVER_KEY')


# print(CONSUMER_KEY, CONSUMER_SECRET, BUSINESS_SHORT_CODE, PASSKEY)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_STORAGE_CLOUD_NAME,
    'API_KEY': CLOUDINARY_STORAGE_API_KEY,
    'API_SECRET': CLOUDINARY_STORAGE_API_SECRET,
}

#DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# these are chamas accoutn credientails



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ['chamaspace.com', 'www.chamaspace.com', '172.105.47.21','localhost']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
CSRF_TRUSTED_ORIGINS = ['https://chamaspace.com']
# Application definition

INSTALLED_APPS = [
'django_crontab',
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # to use humanize in templates

    'authentication',
    'home',
    'Dashboard',
    'user_dashboard',
    'django_twilio',
    'cloudinary_storage',
    'cloudinary',
    'fcm_django',
    'notifications',
    'wallet',
    'pyment_withdraw',
    'mpesa_integration',
    'mathfilters',
    'Goals',
    'chamas',
    'subscriptions',
    'bot',
    'blog',
    'expense_tracker',
    'merry_go_round',
    'support',

    # Third-party apps
    'tinymce',

    'constance',
    'constance.backends.database',
]

# FIREBASE_APP = initialize_app()

FCM_DJANGO_SETTINGS = {
    # default: _('FCM Django')
    "APP_VERBOSE_NAME": "_('FCM Django')",
    # true if you want to have only one active device per registered user at a time
    # default: False
    "ONE_DEVICE_PER_USER": False,
    # devices to which notifications cannot be sent,
    # are deleted upon receiving error response from FCM
    # default: False
    "DELETE_INACTIVE_DEVICES": True,
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'subscriptions.middleware.SubscriptionMiddleware',
    'expense_tracker.middleware.ExpenseTrackerMiddleware',
]

ROOT_URLCONF = 'Chamabora.urls'

LOGIN_REDIRECT_URL = '/dashboard/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'expense_tracker.context_processors.expense_tracker_context',
                'merry_go_round.context_processors.mgr_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'Chamabora.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
FCM_SERVER_KEY = FCM_SERVER_KEY

# Use PostgreSQL for production if DATABASE_URL is available
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME':env('DB_NAME') ,
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),
        }
    }
db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)

# Before development
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME':  '/db/db.sqlite3',
#         # 'NAME': os.path.join(BASE_DIR, 'data', 'db.sqlite3'),
#     }
# }

# After development
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]





# Media files configuration
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Support app specific settings
MAX_UPLOAD_SIZE = 5242880  # 5MB in bytes
ALLOWED_TICKET_ATTACHMENTS = ['.jpg', '.jpeg', '.png', '.pdf', '.txt', '.doc', '.docx']


INFOBIP_API_BASE_URL = "rpvp61.api.infobip.com"
INFOBIP_API_KEY = env('INFOBIP_API_KEY')
INFOBIP_SENDER_ID = env('INFOBIP_SENDER_ID')
# TWILIO_PHONE_NUMBER= 'CHAMABORA'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


CRONJOBS = [
    ('0 5 * * *', 'wallet.cron.my_scheduled_job'),
]

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'width': '100%',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'plugins': '''
        textcolor save link image media preview codesample contextmenu
        table code lists fullscreen insertdatetime nonbreaking
        contextmenu directionality searchreplace wordcount visualblocks
        visualchars code fullscreen autolink lists charmap print hr
        anchor pagebreak
    ''',
    'toolbar1': '''
        fullscreen preview bold italic underline | fontselect fontsizeselect |
        forecolor backcolor | alignleft alignright aligncenter alignjustify |
        indent outdent | bullist numlist | link image media | codesample
    ''',
    'toolbar2': '''
        visualblocks visualchars | charmap hr pagebreak nonbreaking anchor |
        code | table | undo redo | searchreplace | removeformat
    ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
}


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "ChamaBORA",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "ChamaBORA",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "ChamaBORA",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "dist/img/dhb.jpeg",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "dist/img/dhb.jpeg",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the ChamaBORA",

    # Copyright on the footer
    "copyright": "ChamaBORA ",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": "auth.User",

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Stats",  "url": "https://chamaspace.com/dashboard/stats_page1", "permissions": ["auth.view_user"]},
        # {"name": "Distribute Chama Bonus",  "url": "http://www.chamabora.com/wallet/", "permissions": ["auth.view_user"]},
        {"name": "Distribute Chama Bonus",  "url": "https://chamaspace.com/wallet/", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "books"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "books": [{
            "name": "Make Messages",
            "url": "make_messages",
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": False,
}

# ==================== CELERY CONFIGURATION ====================

ENABLE_CELERY = os.getenv('ENABLE_CELERY', 'False').lower() == 'true'

if ENABLE_CELERY:
    try:
        from celery.schedules import crontab
        CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
        CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
        CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', 'Africa/Nairobi')
        CELERY_TASK_SERIALIZER = 'json'
        CELERY_RESULT_SERIALIZER = 'json'
        CELERY_ACCEPT_CONTENT = ['json']

        # Schedule recurring transactions, MGR, and goal reminders
        CELERY_BEAT_SCHEDULE = {
            # Existing expense tracker task
            'process-recurring-transactions-daily': {
                'task': 'expense_tracker.process_recurring_transactions',
                'schedule': crontab(hour=8, minute=0),
                'options': {
                    'expires': 3600,  # Task expires after 1 hour if not executed
                }
            },
            # Goal reminders task - runs at 9:00 AM daily
            'send-goal-reminders-daily': {
                'task': 'goals.send_goal_reminders',
                'schedule': crontab(hour=9, minute=0),
                'options': {
                    'expires': 3600,  # Task expires after 1 hour if not executed
                }
            },

        # Celery configuration for running MGR app

            # CRITICAL: Mark rounds as complete (midnight)
            'mgr-check-complete-rounds': {
                'task': 'mgr.check_and_complete_rounds',
                'schedule': crontab(hour=0, minute=0),  # 12:00 AM (midnight)
                'options': {
                    'expires': 3600,
                }
            },
            
            # NEW CRITICAL TASK: Process payouts for rounds completed yesterday
            # This runs AFTER interest has accrued for one more day
            'mgr-process-completed-round-payouts': {
                'task': 'mgr.process_completed_round_payouts',
                'schedule': crontab(hour=1, minute=0),  # 1:00 AM (one hour after completion check)
                'options': {
                    'expires': 3600,
                }
            },
    
            # CRITICAL DAILY TASKS (6:00 AM - 10:00 AM)           
    
            'mgr-auto-process-contributions': {
                'task': 'mgr.auto_process_contributions',
                'schedule': crontab(hour=6, minute=0),  # 6:00 AM
                'options': {
                    'expires': 3600,  # Task expires after 1 hour
                }
            },
            
            'mgr-mark-missed-contributions': {
                'task': 'mgr.mark_missed_contributions',
                'schedule': crontab(hour=7, minute=0),  # 7:00 AM
                'options': {
                    'expires': 3600,
                }
            },
            
            'mgr-send-contribution-reminders': {
                'task': 'mgr.send_contribution_reminders',
                'schedule': crontab(hour=8, minute=0),  # 8:00 AM
            },
            
            'mgr-send-advance-reminders': {
                'task': 'mgr.send_advance_reminders',
                'schedule': crontab(hour=9, minute=0),  # 9:00 AM
            },
            
            'mgr-send-reservation-reminders': {
                'task': 'mgr.send_reservation_reminders',
                'schedule': crontab(hour=9, minute=30),  # 9:30 AM
            },
            
            'mgr-process-due-payouts': {
                'task': 'mgr.process_due_payouts',
                'schedule': crontab(hour=10, minute=0),  # 10:00 AM
                'options': {
                    'expires': 3600,
                }
            },
            
            # ============================================================
            # EVENING MAINTENANCE TASKS (11:00 PM - 12:00 AM)
            # ============================================================
            
            'mgr-update-trust-scores': {
                'task': 'mgr.update_trust_scores',
                'schedule': crontab(hour=23, minute=0),  # 11:00 PM
            },
            
            'mgr-calculate-daily-interest': {
                'task': 'mgr.calculate_daily_interest',
                'schedule': crontab(hour=23, minute=59),  # 11:59 PM
            },
            
            'mgr-check-complete-rounds': {
                'task': 'mgr.check_and_complete_rounds',
                'schedule': crontab(hour=0, minute=0),  # 12:00 AM (midnight)
                'options': {
                    'expires': 3600,
                }
            },
            
            # ============================================================
            # CLEANUP TASKS (Early Morning)
            # ============================================================
            
            'mgr-cleanup-expired-invitations': {
                'task': 'mgr.cleanup_expired_invitations',
                'schedule': crontab(hour=2, minute=0),  # 2:00 AM
            },
            
            # ============================================================
            # WEEKLY TASKS
            # ============================================================
            
            'mgr-send-weekly-summary': {
                'task': 'mgr.send_weekly_summary',
                'schedule': crontab(
                    hour=8, 
                    minute=0, 
                    day_of_week=1  # Monday
                ),
            },
            
            # ============================================================
            # OPTIONAL: BI-WEEKLY TASKS
            # ============================================================
            
            'mgr-trust-score-audit': {
                'task': 'mgr.update_trust_scores',
                'schedule': crontab(
                    hour=12, 
                    minute=0,
                    day_of_week=0,  # Sunday
                    day_of_month='1-7,15-21'  # First and third Sunday
                ),
            },
            'send-invitation-reminders': {
                'task': 'mgr.send_invitation_reminders',
                'schedule': crontab(
                    hour=10, 
                    minute=0
                    
                ),  # Daily at 10:00 AM
             },
            'notify-expired-invitations': {
                'task': 'mgr.notify_expired_invitations',
                'schedule': crontab(
                    hour=11, 
                    minute=0
                ),  # Daily at 11:00 AM
            },
            'check-pending-invitations-quota': {
                'task': 'mgr.check_pending_invitations_quota',
                'schedule': crontab(
                    hour=9, 
                    minute=0
                    
                ),  # Daily at 9:00 AM
            },
            
        }
        
    except ImportError:
        # Celery dependencies not installed – harmless in prod if intentional
        pass

else:
    # Local dev: run tasks synchronously (no worker/Redis needed)
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True


# ==================== CONSTANCE CONFIGURATION ====================
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_CONFIG = {
    # MGR Settings
    'MGR_DEFAULT_INTEREST_RATE': (
        Decimal('12.00'), 
        'Default annual interest rate for all new rounds (%)',
        Decimal
    ),
    'MGR_TAX_RATE': (
        Decimal('15.00'), 
        'Tax rate on interest earned (% - Kenyan withholding tax on interest)',
        Decimal
    ),
    'ROTATIONAL_MODEL_ENABLED': (
        False, 
        'Enable rotational payout model for private rounds',
        bool
    ),
    'MGR_INVITATION_VALIDITY_DAYS': (
        7, 
        'Number of days before an invitation expires',
        int
    ),
}

CONSTANCE_CONFIG_FIELDSETS = {
    'Merry-Go-Round Settings': (
        'MGR_DEFAULT_INTEREST_RATE',
        'MGR_TAX_RATE',
        'ROTATIONAL_MODEL_ENABLED', 
        'MGR_INVITATION_VALIDITY_DAYS',
    ),
}