# Generated by Django 3.1 on 2022-06-23 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mpesa_deposit_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=2000, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Last Name')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('phone_number', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Phone Number')),
                ('amount', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Amount')),
                ('reference_id', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Reference No.')),
                ('type', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Type')),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Mpesa Transactions History',
            },
        ),
    ]
