# Generated by Django 3.1 on 2022-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesa_deposit_details',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='mpesa_deposit_details',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mpesa_deposit_details',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mpesa_deposit_details',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mpesa_deposit_details',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='mpesa_deposit_details',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='mpesa_deposit_details',
            name='type',
        ),
        migrations.AddField(
            model_name='mpesa_deposit_details',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Check Out ID'),
        ),
        migrations.AddField(
            model_name='mpesa_deposit_details',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Merchant ID'),
        ),
        migrations.AddField(
            model_name='mpesa_deposit_details',
            name='pay_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='mpesa_deposit_details',
            name='phone',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='mpesa_deposit_details',
            name='result_code',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Result Code'),
        ),
    ]
