# Generated by Django 3.2.18 on 2025-08-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_integration', '0002_auto_20220826_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesa_deposit_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
