# Generated by Django 5.2.7 on 2025-12-19 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_national_id', models.CharField(help_text='ID number provided at signup (may be unverified or incorrect)', max_length=20)),
                ('verified_national_id', models.CharField(blank=True, help_text='ID number extracted from verified documents (authoritative)', max_length=20, null=True, unique=True)),
                ('document_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport')], max_length=20)),
                ('id_front_image', models.ImageField(blank=True, help_text='Front of ID or passport bio page', null=True, upload_to='kyc/documents/%Y/%m/')),
                ('id_back_image', models.ImageField(blank=True, help_text='Back of ID (not required for passport)', null=True, upload_to='kyc/documents/%Y/%m/')),
                ('selfie_image', models.ImageField(blank=True, help_text='Live selfie for facial verification', null=True, upload_to='kyc/selfies/%Y/%m/')),
                ('verification_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_required', 'Resubmission Required')], default='not_started', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin reviewer')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason shown to user if rejected')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_correction_count', models.IntegerField(default=0, help_text='Number of times user corrected their declared ID')),
                ('resubmission_count', models.IntegerField(default=0, help_text='Number of times user resubmitted documents')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Profile',
                'verbose_name_plural': 'KYC Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission Requested'), ('id_corrected', 'ID Number Corrected'), ('documents_uploaded', 'Documents Uploaded')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='user_dashboard.kycprofile')),
            ],
            options={
                'verbose_name': 'KYC Audit Log',
                'verbose_name_plural': 'KYC Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['verification_status'], name='user_dashbo_verific_02e4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['verified_national_id'], name='user_dashbo_verifie_aa446b_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['submitted_at'], name='user_dashbo_submitt_f868db_idx'),
        ),
    ]
