# Generated by Django 5.2.7 on 2025-12-29 19:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20250803_1108'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('notification_id', models.CharField(max_length=100)),
                ('dismissed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('dismissed', 'Dismissed'), ('snoozed', 'Snoozed'), ('deleted', 'Deleted')], default='dismissed', max_length=20)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dismissed_at'],
                'indexes': [models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_0bfa34_idx'), models.Index(fields=['user', 'snooze_until'], name='notificatio_user_id_fd262e_idx')],
                'unique_together': {('user', 'notification_id')},
            },
        ),
    ]
